
CREATE OR REPLACE VIEW CATEGORY_PRODUCTS AS
SELECT
    CAT_ID ID, CAT_NAME CATEGORY,
    COUNT( PRODUCT_ID ) PRODUCTS
FROM
    PRODUCT 
INNER JOIN CATEGORY
        USING(CAT_ID)
GROUP BY
    CAT_ID, CAT_NAME
ORDER BY
    CAT_ID;
/
    
CREATE OR REPLACE VIEW SHOP_VIEW AS
SELECT
    SHOP_ID ID, SHOP_NAME SHOP, FULLNAME TRADER,
    COUNT( PRODUCT_ID ) PRODUCTS
FROM PRODUCT 
INNER JOIN SHOP USING(SHOP_ID)
INNER JOIN USERS ON SHOP.TRADER_ID = USERS.USER_ID   
GROUP BY
    SHOP_ID, SHOP_NAME, FULLNAME
ORDER BY
    SHOP_ID;
/


CREATE OR REPLACE VIEW PRODUCTS_VIEW AS
SELECT PRODUCT_ID ID, PRODUCT_NAME NAME, PRODUCT_TYPE TYPE, 
FULLNAME TRADER, SHOP_NAME SHOP, STOCK_AVAILABLE STOCK, 
PRODUCT_PRICE PRICE, MIN_ORDER, MAX_ORDER, PRODUCT_DESCRIPTION
DESCRIPTION, ALLERGY_INFORMATION ALLERGY_INFO FROM PRODUCT 
INNER JOIN SHOP USING(SHOP_ID) INNER JOIN USERS ON 
SHOP.TRADER_ID = USERS.USER_ID;
/



CREATE OR REPLACE VIEW WEEKLY_SALES_ALL_VIEW AS
SELECT DISTINCT o.INVOICE_NO, TO_CHAR(ORDER_DATE, 'DAY, MM/DD/YYYY') DAY, 
c.SLOT_INFO COLLECTION_SLOT, o.COLLECTION_DATE, u.FULLNAME CUSTOMER, p.PAYMENT_AMOUNT AMOUNT
FROM ORDERS o, ORDER_DETAILS od, PAYMENT p, COLLECTION_SLOT c, USERS u
WHERE o.INVOICE_NO = od.INVOICE_NO AND o.PAYMENT_ID = p.PAYMENT_ID AND o.SLOT_NO = c.SLOT_NO
AND o.USER_ID = u.USER_ID
AND to_date(to_char(o.ORDER_DATE,'MM.DD.YYYY'), 'MM/DD/YYYY') >= (SYSDATE-7);
/

CREATE OR REPLACE VIEW WEEKLY_SALES_DISTINCT_VIEW AS
SELECT DAY, SUM(AMOUNT) SALE_AMOUNT
FROM WEEKLY_SALES_ALL_VIEW
GROUP BY DAY
ORDER BY DAY DESC;
/

CREATE OR REPLACE VIEW MONTHLY_SALES_ALL_VIEW AS
SELECT DISTINCT o.INVOICE_NO, TO_CHAR(ORDER_DATE, 'DAY, MM/DD/YYYY') DAY, 
c.SLOT_INFO COLLECTION_SLOT, o.COLLECTION_DATE, u.FULLNAME CUSTOMER, p.PAYMENT_AMOUNT AMOUNT
FROM ORDERS o, ORDER_DETAILS od, PAYMENT p, COLLECTION_SLOT c, USERS u
WHERE o.INVOICE_NO = od.INVOICE_NO AND o.PAYMENT_ID = p.PAYMENT_ID AND o.SLOT_NO = c.SLOT_NO
AND o.USER_ID = u.USER_ID
AND to_date(to_char(o.ORDER_DATE,'MM.DD.YYYY'), 'MM/DD/YYYY') >= (SYSDATE-30);
/

CREATE OR REPLACE VIEW MONTHLY_SALES_DISTINCT_VIEW AS
SELECT DAY, SUM(AMOUNT) SALE_AMOUNT
FROM MONTHLY_SALES_ALL_VIEW
GROUP BY DAY
ORDER BY DAY DESC;
/

CREATE OR REPLACE VIEW DAILY_SALES_ALL_VIEW AS
SELECT DISTINCT o.INVOICE_NO, TO_CHAR(ORDER_DATE, 'DAY, MM/DD/YYYY') DAY, c.SLOT_INFO COLLECTION_SLOT, 
o.COLLECTION_DATE, u.FULLNAME CUSTOMER, p.PAYMENT_AMOUNT AMOUNT
FROM ORDERS o, ORDER_DETAILS od, PAYMENT p, COLLECTION_SLOT c, USERS u
WHERE o.INVOICE_NO = od.INVOICE_NO AND o.PAYMENT_ID = p.PAYMENT_ID AND o.SLOT_NO = c.SLOT_NO
AND o.USER_ID = u.USER_ID
AND to_date(to_char(o.ORDER_DATE,'MM.DD.YYYY'), 'MM/DD/YYYY') >= (SYSDATE-1);
/

CREATE OR REPLACE VIEW DAILY_SALES_DISTINCT_VIEW AS
SELECT DAY, SUM(AMOUNT) SALE_AMOUNT
FROM DAILY_SALES_ALL_VIEW
GROUP BY DAY
ORDER BY DAY DESC;
/